name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    # ========================
    # Checkout
    # ========================
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # ========================
    # Install Dependencies
    # ========================

    # Linux
    - name: Install Linux deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          libopenal-dev \
          libflac-dev \
          libvorbis-dev \
          libudev-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxi-dev \
          mesa-common-dev \
          libgl1-mesa-dev \
          libfreetype6-dev \
          g++

    # macOS
    - name: Install macOS deps
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake sfml openal-soft flac libvorbis

    # Windows
    - name: Setup MSVC + CMake
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    # ========================
    # CMake Configure
    # ========================

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCPACK_GENERATOR=${{ matrix.os == 'windows-latest' && 'ZIP' || 'TGZ' }}
    # ========================
    # Build
    # ========================

    - name: Build project
      run: cmake --build build --config Release --parallel

    # ========================
    # Packaging
    # ========================

    - name: Create package
      run: |
        cd build
        cpack -G ${{ runner.os == 'Windows' && 'ZIP' || 'TGZ' }}

    # ========================
    # Release upload
    # ========================

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: build/_CPack_Packages/**/*.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}